### ISSUE TITLE
[question] how is your screenshot minibuffer popup configured?

### ISSUE THREAD

**Issue by stardiviner** [isamert/sozluk.el#1]
As the title described. I'm curioused and want to configure same.

**Comment by isamert** [comment]
Hi @stardiviner

I used [mini-frame](https://github.com/muffinmad/emacs-mini-frame) for the pop-up minibuffer. I also use [vertico](https://github.com/minad/vertico) for command completion and [marginalia](https://github.com/minad/marginalia) for the annotations.
